<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
    {
        "@context": "http://schema.org",
        "@type": "LocalBusiness",
        "name": "yoursite",
        "sameAs": [
            "https://www.facebook.com/yoursite/"
        ],
        "priceRange": "$ - $$$",
        "image": "https://www.yoursite.com/images/header-logo.png",
        "telephone": "702-444-4444",
        "email": "yoursite@gmail.com",
        "address": {
            "@type": "PostalAddress",
            "streetAddress": "street",
            "addressLocality": "city",
            "addressRegion": "NY",
            "addressCountry": "US",
            "postalCode": "84123"
        },
        "geo": {
            "@type": "GeoCoordinates",
            "latitude": "0.0",
            "longitude": "-1.0"
        },
        "url": "https://www.yoursite.com/",
        "review": {
            "@type": "Review",
            "author": {
                "@type": "Person",
                "name": "Jane D."
            },
            "reviewRating": {
                "@type": "Rating",
                "ratingValue": "5",
                "bestRating": "5"
            },
            "reviewBody": "Review message"
        }
    }
</script>